receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  prometheus:
    endpoint: "0.0.0.0:9090"
    # namespace: dashfrog
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true
processors:
  batch:
    send_batch_size: 1000  # Tune the batch size for more efficient exporting
    timeout: 1s

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/ping"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers:
        - otlp
      exporters:
        - debug
        - prometheus