services:
  postgresql:
    hostname: postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev-pwd*
      - POSTGRES_DB=dashfrog

  clickhouse:
    hostname: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "9000:9000"
      - "8443:8443"
      - "8123:8123"
    environment:
      - CLICKHOUSE_USER=dev
      - CLICKHOUSE_PASSWORD=dev-pwd*
      - CLICKHOUSE_DB=dashfrog

  redis:
    hostname: redis
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  prometheus:
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/prometheus.yaml
    command:
      - "--config.file=/prometheus.yaml"
    ports:
      - "9090:9090"

  collector:
    image: ghcr.io/towlabs/dashfrog/collector:latest
    build:
      context: collector
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12001:12001"
      - "13133:13133"
    volumes:
      - ./collector-config.yaml:/otelcol/collector-config.yaml

  backend:
    image: ghcr.io/towlabs/dashfrog/backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - postgresql
      - clickhouse
      - redis
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/towlabs/dashfrog/frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend