global:
  scrape_interval: 15s
  #scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
runtime:
  gogc: 75
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['collector:9090']
otlp:
  translation_strategy: UnderscoreEscapingWithSuffixes