{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dashfrog_kube.fullname" . }}-backend
  labels:
    {{- include "dashfrog_kube.labels" . | nindent 4 }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "dashfrog_kube.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "dashfrog_kube.selectorLabels" . | nindent 8 }}
        component: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-backend.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ include "dashfrog_kube.serviceAccountName" $ }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.backend.securityContext | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.config.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.backend.config.port }}"
            - name: RELEASE
              value: "{{ .Values.backend.config.release }}"
            {{- if .Values.clickhouse.enabled }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dashfrog_kube.fullname" . }}-secret
                  key: clickhouse-password
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dashfrog_kube.fullname" . }}-secret
                  key: postgresql-password
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: {{ include "dashfrog_kube.fullname" . }}-backend-config
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
