{{- if .Values.collector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dashfrog_kube.fullname" . }}-collector
  labels:
    {{- include "dashfrog_kube.labels" . | nindent 4 }}
    component: collector
spec:
  replicas: {{ .Values.collector.replicaCount }}
  selector:
    matchLabels:
      {{- include "dashfrog_kube.selectorLabels" . | nindent 6 }}
      component: collector
  template:
    metadata:
      labels:
        {{- include "dashfrog_kube.selectorLabels" . | nindent 8 }}
        component: collector
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ include "dashfrog_kube.serviceAccountName" $ }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.collector.securityContext | nindent 8 }}
      containers:
        - name: collector
          image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          args:
            - "--config"
            - "/otelcol/collector-config.yaml"
          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.collector.config.otlpGrpcPort }}
              protocol: TCP
            - name: otlp-http
              containerPort: {{ .Values.collector.config.otlpHttpPort }}
              protocol: TCP
            - name: prometheus
              containerPort: {{ .Values.collector.config.prometheusPort }}
              protocol: TCP
            - name: health-check
              containerPort: {{ .Values.collector.config.healthCheckPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
          volumeMounts:
            - name: collector-config
              mountPath: /otelcol/collector-config.yaml
              subPath: collector-config.yaml
          # Temporarily disable probes for debugging
          # livenessProbe:
          #   httpGet:
          #     path: /ping
          #     port: health-check
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /ping
          #     port: health-check
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   failureThreshold: 3
      volumes:
        - name: collector-config
          configMap:
            name: {{ include "dashfrog_kube.fullname" . }}-collector-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
