{{- if .Values.collector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashfrog_kube.fullname" . }}-collector-config
  labels:
    {{- include "dashfrog_kube.labels" . | nindent 4 }}
    component: collector
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    exporters:
      debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      prometheus:
        endpoint: "0.0.0.0:9090"
        # namespace: dashfrog
        resource_to_telemetry_conversion:
          enabled: false
    processors:
      batch:
        send_batch_size: 1000  # Tune the batch size for more efficient exporting
        timeout: 1s
      transform/keep-dashfrog-labels:
        error_mode: ignore
        metric_statements:
          - context: datapoint
            statements:
              - keep_matching_keys(attributes, "^dashfrog\\.label.*$")
          - context: resource
            statements:
              - keep_matching_keys(attributes, "^dashfrog\\.label.*$")

    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
        path: "/ping"
        check_collector_pipeline:
          enabled: true
          interval: "5m"
          exporter_failure_threshold: 5

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - batch
            - transform/keep-dashfrog-labels
          exporters:
            - debug
            - prometheus
{{- end }}
