{{- if .Values.collector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashfrog_kube.fullname" . }}-collector-config
  labels:
    {{- include "dashfrog_kube.labels" . | nindent 4 }}
    component: collector
data:
  collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:{{ .Values.collector.config.otlpGrpcPort }}
          http:
            endpoint: 0.0.0.0:{{ .Values.collector.config.otlpHttpPort }}

    exporters:
      debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      prometheusremotewrite:
        endpoint: "http://{{ include "dashfrog_kube.fullname" . }}-prometheus:{{ .Values.prometheus.service.port }}/api/v1/write"
        timeout: 10s
        # You can configure retry / queue settings if needed
        remote_write_queue:
          enabled: true
          num_consumers: 1
          queue_size: 5000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
        resource_to_telemetry_conversion:
          enabled: true
        send_metadata: true
        protobuf_message: io.prometheus.write.v2.Request
        export_created_metric: true
        enable_native_histograms: true

      # Metadata-only exporter for all metrics
      prometheus:
        endpoint: "0.0.0.0:{{ .Values.collector.config.prometheusPort }}"
        enable_open_metrics: true
        resource_to_telemetry_conversion:
          enabled: true
        namespace: "meta"  # Optional, keeps metadata visually separated
    processors:
      batch:
        send_batch_size: 1000  # Tune the batch size for more efficient exporting
        timeout: 1s

    extensions:
      health_check:
        endpoint: "0.0.0.0:{{ .Values.collector.config.healthCheckPort }}"
        path: "/ping"
        check_collector_pipeline:
          enabled: true
          interval: "5m"
          exporter_failure_threshold: 5

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - debug
            - prometheusremotewrite
{{- end }}
