{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dashfrog_kube.fullname" . }}-prometheus-config
  labels:
    {{- include "dashfrog_kube.labels" . | nindent 4 }}
    component: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.scrapeInterval }}
      scrape_timeout: {{ .Values.prometheus.config.scrapeTimeout }}
      scrape_protocols:
      - OpenMetricsText1.0.0
      - OpenMetricsText0.0.1
      - PrometheusText1.0.0
      - PrometheusText0.0.4
    runtime:
      gogc: 75
    alerting:
      alertmanagers:
      - follow_redirects: true
        enable_http2: true
        scheme: http
        timeout: 10s
        api_version: v2
        static_configs:
        - targets: []
    scrape_configs:
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['{{ include "dashfrog_kube.fullname" . }}-collector:{{ .Values.collector.config.prometheusPort }}']
    otlp:
      translation_strategy: UnderscoreEscapingWithSuffixes
{{- end }}
