{{/*
DEPRECATED: This file is no longer used.
PostgreSQL now uses a StatefulSet with volumeClaimTemplates (see postgresql-deployment.yaml).
StatefulSets automatically manage PVCs, ensuring stable storage across pod recreations.

This file is kept for reference but will not create any resources.
To fully remove it, delete this file from the templates directory.
*/}}
{{- if false }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dashfrog_kube.fullname" . }}-postgresql-pvc
  labels:
    {{- include "dashfrog_kube.labels" . | nindent 4 }}
    component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  {{- end }}
{{- end }}
