{{/*
DEPRECATED: This file is no longer used.
Prometheus now uses a StatefulSet with volumeClaimTemplates (see prometheus-deployment.yaml).
StatefulSets automatically manage PVCs, ensuring stable storage across pod recreations.

This file is kept for reference but will not create any resources.
To fully remove it, delete this file from the templates directory.
*/}}
{{- if false }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dashfrog_kube.fullname" . }}-prometheus-pvc
  labels:
    {{- include "dashfrog_kube.labels" . | nindent 4 }}
    component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
  {{- if .Values.prometheus.persistence.storageClass }}
  storageClassName: {{ .Values.prometheus.persistence.storageClass }}
  {{- end }}
{{- end }}
