"""update notebook

Revision ID: b209f644d09d
Revises: bf277d8d0950
Create Date: 2025-10-27 17:14:26.447096

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b209f644d09d'
down_revision: str | Sequence[str] | None = 'bf277d8d0950'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('time_window', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'time_window')
    # ### end Alembic commands ###
