### GET labels
GET 0.0.0.0:8080/api/labels
### GET labels with hidden
GET 0.0.0.0:8080/api/labels?with_hidden=true
### Scrape labels
GET 0.0.0.0:8080/api/labels/scrape


### Scrape metrics
GET 0.0.0.0:8080/api/metrics/scrape

### List metrics
GET 0.0.0.0:8080/api/metrics/

### Proxy prom query
POST 0.0.0.0:8080/api/metrics/query
Content-Type: application/json

{
  "query": "sum by (status) (workflow_status_total)",
  "from_date": "2025-09-23T13:59:54.000Z",
  "to_date": "2025-10-20T13:59:54.578Z"
}