"""notebook cols

Revision ID: 9c7749d989a7
Revises: 03da39980edf
Create Date: 2025-11-27 13:53:42.159828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c7749d989a7'
down_revision: Union[str, None] = '03da39980edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_event_event_dt_brin'), table_name='timeline_event', postgresql_using='brin')
    op.drop_table('timeline_event')
    op.add_column('notebook', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notebook', sa.Column('flow_blocks_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notebook', sa.Column('metric_blocks_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebook', 'metric_blocks_filters')
    op.drop_column('notebook', 'flow_blocks_filters')
    op.drop_column('notebook', 'is_public')
    op.create_table('timeline_event',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('markdown', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tenant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blocks', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('timeline_event_pkey'))
    )
    op.create_index(op.f('ix_timeline_event_event_dt_brin'), 'timeline_event', ['event_dt'], unique=False, postgresql_using='brin')
    # ### end Alembic commands ###
