# Go modules for Collector core: https://pkg.go.dev/go.opentelemetry.io/collector
# Go modules for Collector contrib: https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib

dist:
  name: otelcol-dashfrog
  description: OTel Collector for Dashfrog
  output_path: ./otelcol-dashfrog


receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.136.0

processors:
  - gomod:  go.opentelemetry.io/collector/processor/batchprocessor v0.136.0

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter v0.136.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.136.0