name: Collector branch deploy
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'collector'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAMESPACE: ${{ github.repository_owner }}
      IMAGE_NAME: dashfrog/collector
      TAG: ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build collector image
        run: |
          docker compose -f docker-compose.yml build collector
      - name: Tag images
        run: |
          docker tag ${REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest ${REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:${TAG}

      - name: Push images to GHCR
        run: |
          docker push ${REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:${TAG}
          docker push ${REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest
